from __future__ import annotations

import copy
import re
from pathlib import Path

import yaml

SOURCE_ROOT = Path('content/EN-TO-RW/EN-TO-RW')
LANGUAGES = {
    'ru': {'folder': 'RU-TO-RW', 'map': {
        'How do you say': 'Как сказать', 'in Kinyarwanda?': 'на киньяруанда?', 'What is': 'Что такое', 'What does': 'Что означает', 'mean?': 'означает?',
        'Translate this lesson term': 'Переведите термин этого урока', 'Answer': 'Ответ', 'Question': 'Вопрос', 'Practice': 'Практика', 'Learn': 'Учить',
        'Listen': 'Слушать', 'Read': 'Читать', 'Write': 'Писать', 'Speak': 'Говорить', 'Choose': 'Выберите', 'Correct': 'Правильный', 'Word': 'Слово', 'Sentence': 'Предложение',
        'Greetings': 'Приветствия', 'Numbers': 'Числа', 'Family': 'Семья', 'Colors': 'Цвета', 'Animals': 'Животные', 'Food': 'Еда', 'Daily Routines': 'Ежедневные дела', 'Weather': 'Погода', 'Clothing': 'Одежда', 'House': 'Дом', 'Travel': 'Путешествия', 'Shopping': 'Покупки', 'Restaurant': 'Ресторан', 'Directions': 'Направления', 'Emotions': 'Эмоции', 'Past Tense': 'Прошедшее время', 'Future Tense': 'Будущее время', 'Conditionals': 'Условные предложения', 'Opinions': 'Мнения', 'Storytelling': 'Рассказы', 'Culture': 'Культура', 'Days': 'Дни', 'Business': 'Бизнес', 'Debates': 'Дебаты', 'Negotiations': 'Переговоры', 'Fluency': 'Свободная речь',
        'Dog': 'Собака', 'Cat': 'Кошка', 'Cow': 'Корова', 'Goat': 'Коза', 'Sheep': 'Овца', 'Pig': 'Свинья', 'Chicken': 'Курица', 'Rabbit': 'Кролик', 'Bird': 'Птица', 'Lion': 'Лев', 'Elephant': 'Слон', 'Fish': 'Рыба', 'Bee': 'Пчела', 'eats': 'ест', 'drinks': 'пьёт', 'sleeps': 'спит', 'runs': 'бегает', 'flies': 'летает', 'swims': 'плавает', 'plays': 'играет', 'grass': 'трава', 'water': 'вода', 'meat': 'мясо', 'milk': 'молоко', 'Left': 'Лево', 'Right': 'Право', 'Straight': 'Прямо', 'Front': 'Спереди', 'Behind': 'Сзади', 'Back': 'Назад', 'Near': 'Рядом', 'Far': 'Далеко', 'Turn left': 'Поверните налево', 'Turn right': 'Поверните направо', 'Go straight': 'Идите прямо', 'Go back': 'Вернитесь', 'Cross the street': 'Перейдите улицу', 'Hello': 'Здравствуйте', 'Goodbye': 'До свидания', 'Good morning': 'Доброе утро', 'Good evening': 'Добрый вечер', 'How are you?': 'Как дела?', 'I am fine': 'У меня всё хорошо', 'Tomorrow': 'Завтра', 'Yesterday': 'Вчера', 'Always': 'Всегда', 'Never': 'Никогда', 'Before': 'До', 'After': 'После', 'Blue': 'Синий', 'Red': 'Красный', 'Green': 'Зелёный', 'Yellow': 'Жёлтый', 'Black': 'Чёрный', 'White': 'Белый', 'Orange': 'Оранжевый', 'Brown': 'Коричневый', 'Purple': 'Фиолетовый', 'Happy': 'Счастливый', 'Sad': 'Грустный', 'Angry': 'Злой', 'Scared': 'Испуганный', 'Name': 'Имя', 'Date': 'Дата', 'Time': 'Время', 'Friend': 'Друг', 'Mother': 'Мать', 'Father': 'Отец', 'Brother': 'Брат', 'Sister': 'Сестра', 'Child': 'Ребёнок', 'Children': 'Дети', 'Home': 'Дом', 'Work': 'Работа', 'business': 'бизнес', 'company': 'компания', 'employee': 'сотрудник', 'employer': 'работодатель', 'manager': 'менеджер', 'client': 'клиент', 'meeting': 'встреча', 'project': 'проект', 'product': 'продукт', 'service': 'услуга', 'office': 'офис', 'price': 'цена', 'cost': 'стоимость', 'offer': 'предложение', 'agreement': 'соглашение', 'contract': 'контракт', 'market': 'рынок', 'school': 'школа', 'hospital': 'больница', 'bank': 'банк', 'street': 'улица', 'house': 'дом', 'room': 'комната', 'door': 'дверь', 'window': 'окно',
    }},
    'hi': {'folder': 'HI-TO-RW', 'map': {
        'How do you say': 'कैसे कहते हैं', 'in Kinyarwanda?': 'किन्यारवांडा में?', 'What is': 'क्या है', 'What does': 'का अर्थ क्या है', 'mean?': 'का अर्थ?', 'Translate this lesson term': 'इस पाठ के शब्द का अनुवाद करें', 'Answer': 'उत्तर', 'Question': 'प्रश्न', 'Practice': 'अभ्यास', 'Learn': 'सीखें', 'Listen': 'सुनें', 'Read': 'पढ़ें', 'Write': 'लिखें', 'Speak': 'बोलें', 'Choose': 'चुनें', 'Correct': 'सही', 'Word': 'शब्द', 'Sentence': 'वाक्य',
        'Greetings': 'अभिवादन', 'Numbers': 'संख्याएँ', 'Family': 'परिवार', 'Colors': 'रंग', 'Animals': 'जानवर', 'Food': 'भोजन', 'Daily Routines': 'दैनिक दिनचर्या', 'Weather': 'मौसम', 'Clothing': 'कपड़े', 'House': 'घर', 'Travel': 'यात्रा', 'Shopping': 'खरीदारी', 'Restaurant': 'रेस्तराँ', 'Directions': 'दिशाएँ', 'Emotions': 'भावनाएँ', 'Past Tense': 'भूतकाल', 'Future Tense': 'भविष्यकाल', 'Conditionals': 'शर्त वाले वाक्य', 'Opinions': 'राय', 'Storytelling': 'कहानी कहना', 'Culture': 'संस्कृति', 'Days': 'दिन', 'Business': 'व्यवसाय', 'Debates': 'बहस', 'Negotiations': 'बातचीत', 'Fluency': 'प्रवाह',
        'Dog': 'कुत्ता', 'Cat': 'बिल्ली', 'Cow': 'गाय', 'Goat': 'बकरी', 'Sheep': 'भेड़', 'Pig': 'सूअर', 'Chicken': 'मुर्गी', 'Rabbit': 'खरगोश', 'Bird': 'पक्षी', 'Lion': 'शेर', 'Elephant': 'हाथी', 'Fish': 'मछली', 'Bee': 'मधुमक्खी', 'eats': 'खाता है', 'drinks': 'पीता है', 'sleeps': 'सोता है', 'runs': 'दौड़ता है', 'flies': 'उड़ता है', 'swims': 'तैरता है', 'plays': 'खेलता है', 'grass': 'घास', 'water': 'पानी', 'meat': 'मांस', 'milk': 'दूध', 'Left': 'बायाँ', 'Right': 'दायाँ', 'Straight': 'सीधा', 'Front': 'सामने', 'Behind': 'पीछे', 'Back': 'वापस', 'Near': 'पास', 'Far': 'दूर', 'Turn left': 'बाएँ मुड़ें', 'Turn right': 'दाएँ मुड़ें', 'Go straight': 'सीधे जाएँ', 'Go back': 'वापस जाएँ', 'Cross the street': 'सड़क पार करें', 'Hello': 'नमस्ते', 'Goodbye': 'अलविदा', 'Good morning': 'सुप्रभात', 'Good evening': 'शुभ संध्या', 'How are you?': 'आप कैसे हैं?', 'I am fine': 'मैं ठीक हूँ', 'Tomorrow': 'कल', 'Yesterday': 'कल', 'Always': 'हमेशा', 'Never': 'कभी नहीं', 'Before': 'पहले', 'After': 'बाद में', 'Blue': 'नीला', 'Red': 'लाल', 'Green': 'हरा', 'Yellow': 'पीला', 'Black': 'काला', 'White': 'सफेद', 'Orange': 'नारंगी', 'Brown': 'भूरा', 'Purple': 'बैंगनी', 'Happy': 'खुश', 'Sad': 'दुखी', 'Angry': 'गुस्से में', 'Scared': 'डरा हुआ', 'Name': 'नाम', 'Date': 'तारीख', 'Time': 'समय', 'Friend': 'दोस्त', 'Mother': 'माँ', 'Father': 'पिता', 'Brother': 'भाई', 'Sister': 'बहन', 'Child': 'बच्चा', 'Children': 'बच्चे', 'Home': 'घर', 'Work': 'काम', 'business': 'व्यवसाय', 'company': 'कंपनी', 'employee': 'कर्मचारी', 'employer': 'नियोक्ता', 'manager': 'प्रबंधक', 'client': 'ग्राहक', 'meeting': 'बैठक', 'project': 'परियोजना', 'product': 'उत्पाद', 'service': 'सेवा', 'office': 'कार्यालय', 'price': 'कीमत', 'cost': 'लागत', 'offer': 'प्रस्ताव', 'agreement': 'समझौता', 'contract': 'अनुबंध', 'market': 'बाज़ार', 'school': 'स्कूल', 'hospital': 'अस्पताल', 'bank': 'बैंक', 'street': 'सड़क', 'house': 'घर', 'room': 'कमरा', 'door': 'दरवाज़ा', 'window': 'खिड़की',
    }},
    'tr': {'folder': 'TR-TO-RW', 'map': {
        'How do you say': 'Nasıl denir', 'in Kinyarwanda?': 'Kinyarwanda dilinde?', 'What is': 'Nedir', 'What does': 'Ne anlama gelir', 'mean?': 'anlamına gelir?', 'Translate this lesson term': 'Bu ders terimini çevirin', 'Answer': 'Cevap', 'Question': 'Soru', 'Practice': 'Pratik', 'Learn': 'Öğren', 'Listen': 'Dinle', 'Read': 'Oku', 'Write': 'Yaz', 'Speak': 'Konuş', 'Choose': 'Seç', 'Correct': 'Doğru', 'Word': 'Kelime', 'Sentence': 'Cümle',
        'Greetings': 'Selamlaşma', 'Numbers': 'Sayılar', 'Family': 'Aile', 'Colors': 'Renkler', 'Animals': 'Hayvanlar', 'Food': 'Yemek', 'Daily Routines': 'Günlük rutinler', 'Weather': 'Hava durumu', 'Clothing': 'Giyim', 'House': 'Ev', 'Travel': 'Seyahat', 'Shopping': 'Alışveriş', 'Restaurant': 'Restoran', 'Directions': 'Yönler', 'Emotions': 'Duygular', 'Past Tense': 'Geçmiş zaman', 'Future Tense': 'Gelecek zaman', 'Conditionals': 'Koşullar', 'Opinions': 'Görüşler', 'Storytelling': 'Hikâye anlatımı', 'Culture': 'Kültür', 'Days': 'Günler', 'Business': 'İş dünyası', 'Debates': 'Tartışmalar', 'Negotiations': 'Müzakereler', 'Fluency': 'Akıcılık',
        'Dog': 'Köpek', 'Cat': 'Kedi', 'Cow': 'İnek', 'Goat': 'Keçi', 'Sheep': 'Koyun', 'Pig': 'Domuz', 'Chicken': 'Tavuk', 'Rabbit': 'Tavşan', 'Bird': 'Kuş', 'Lion': 'Aslan', 'Elephant': 'Fil', 'Fish': 'Balık', 'Bee': 'Arı', 'eats': 'yer', 'drinks': 'içer', 'sleeps': 'uyur', 'runs': 'koşar', 'flies': 'uçar', 'swims': 'yüzer', 'plays': 'oynar', 'grass': 'çimen', 'water': 'su', 'meat': 'et', 'milk': 'süt', 'Left': 'Sol', 'Right': 'Sağ', 'Straight': 'Düz', 'Front': 'Ön', 'Behind': 'Arka', 'Back': 'Geri', 'Near': 'Yakın', 'Far': 'Uzak', 'Turn left': 'Sola dönün', 'Turn right': 'Sağa dönün', 'Go straight': 'Düz gidin', 'Go back': 'Geri dönün', 'Cross the street': 'Caddeyi geçin', 'Hello': 'Merhaba', 'Goodbye': 'Hoşça kal', 'Good morning': 'Günaydın', 'Good evening': 'İyi akşamlar', 'How are you?': 'Nasılsın?', 'I am fine': 'İyiyim', 'Tomorrow': 'Yarın', 'Yesterday': 'Dün', 'Always': 'Her zaman', 'Never': 'Asla', 'Before': 'Önce', 'After': 'Sonra', 'Blue': 'Mavi', 'Red': 'Kırmızı', 'Green': 'Yeşil', 'Yellow': 'Sarı', 'Black': 'Siyah', 'White': 'Beyaz', 'Orange': 'Turuncu', 'Brown': 'Kahverengi', 'Purple': 'Mor', 'Happy': 'Mutlu', 'Sad': 'Üzgün', 'Angry': 'Kızgın', 'Scared': 'Korkmuş', 'Name': 'İsim', 'Date': 'Tarih', 'Time': 'Saat', 'Friend': 'Arkadaş', 'Mother': 'Anne', 'Father': 'Baba', 'Brother': 'Erkek kardeş', 'Sister': 'Kız kardeş', 'Child': 'Çocuk', 'Children': 'Çocuklar', 'Home': 'Ev', 'Work': 'İş', 'business': 'iş', 'company': 'şirket', 'employee': 'çalışan', 'employer': 'işveren', 'manager': 'yönetici', 'client': 'müşteri', 'meeting': 'toplantı', 'project': 'proje', 'product': 'ürün', 'service': 'hizmet', 'office': 'ofis', 'price': 'fiyat', 'cost': 'maliyet', 'offer': 'teklif', 'agreement': 'anlaşma', 'contract': 'sözleşme', 'market': 'pazar', 'school': 'okul', 'hospital': 'hastane', 'bank': 'banka', 'street': 'sokak', 'house': 'ev', 'room': 'oda', 'door': 'kapı', 'window': 'pencere',
    }},
    'nl': {'folder': 'NL-TO-RW', 'map': {
        'How do you say': 'Hoe zeg je', 'in Kinyarwanda?': 'in het Kinyarwanda?', 'What is': 'Wat is', 'What does': 'Wat betekent', 'mean?': 'betekent?', 'Translate this lesson term': 'Vertaal deze lesterm', 'Answer': 'Antwoord', 'Question': 'Vraag', 'Practice': 'Oefenen', 'Learn': 'Leren', 'Listen': 'Luisteren', 'Read': 'Lezen', 'Write': 'Schrijven', 'Speak': 'Spreken', 'Choose': 'Kiezen', 'Correct': 'Juist', 'Word': 'Woord', 'Sentence': 'Zin',
        'Greetings': 'Begroetingen', 'Numbers': 'Getallen', 'Family': 'Familie', 'Colors': 'Kleuren', 'Animals': 'Dieren', 'Food': 'Eten', 'Daily Routines': 'Dagelijkse routines', 'Weather': 'Weer', 'Clothing': 'Kleding', 'House': 'Huis', 'Travel': 'Reizen', 'Shopping': 'Winkelen', 'Restaurant': 'Restaurant', 'Directions': 'Richtingen', 'Emotions': 'Emoties', 'Past Tense': 'Verleden tijd', 'Future Tense': 'Toekomende tijd', 'Conditionals': 'Voorwaardelijke zinnen', 'Opinions': 'Meningen', 'Storytelling': 'Verhalen vertellen', 'Culture': 'Cultuur', 'Days': 'Dagen', 'Business': 'Zakendoen', 'Debates': 'Debatten', 'Negotiations': 'Onderhandelingen', 'Fluency': 'Vloeiendheid',
        'Dog': 'Hond', 'Cat': 'Kat', 'Cow': 'Koe', 'Goat': 'Geit', 'Sheep': 'Schaap', 'Pig': 'Varken', 'Chicken': 'Kip', 'Rabbit': 'Konijn', 'Bird': 'Vogel', 'Lion': 'Leeuw', 'Elephant': 'Olifant', 'Fish': 'Vis', 'Bee': 'Bij', 'eats': 'eet', 'drinks': 'drinkt', 'sleeps': 'slaapt', 'runs': 'rent', 'flies': 'vliegt', 'swims': 'zwemt', 'plays': 'speelt', 'grass': 'gras', 'water': 'water', 'meat': 'vlees', 'milk': 'melk', 'Left': 'Links', 'Right': 'Rechts', 'Straight': 'Rechtdoor', 'Front': 'Voor', 'Behind': 'Achter', 'Back': 'Terug', 'Near': 'Dichtbij', 'Far': 'Ver', 'Turn left': 'Ga linksaf', 'Turn right': 'Ga rechtsaf', 'Go straight': 'Ga rechtdoor', 'Go back': 'Ga terug', 'Cross the street': 'Steek de straat over', 'Hello': 'Hallo', 'Goodbye': 'Tot ziens', 'Good morning': 'Goedemorgen', 'Good evening': 'Goedenavond', 'How are you?': 'Hoe gaat het?', 'I am fine': 'Het gaat goed met mij', 'Tomorrow': 'Morgen', 'Yesterday': 'Gisteren', 'Always': 'Altijd', 'Never': 'Nooit', 'Before': 'Voor', 'After': 'Na', 'Blue': 'Blauw', 'Red': 'Rood', 'Green': 'Groen', 'Yellow': 'Geel', 'Black': 'Zwart', 'White': 'Wit', 'Orange': 'Oranje', 'Brown': 'Bruin', 'Purple': 'Paars', 'Happy': 'Blij', 'Sad': 'Verdrietig', 'Angry': 'Boos', 'Scared': 'Bang', 'Name': 'Naam', 'Date': 'Datum', 'Time': 'Tijd', 'Friend': 'Vriend', 'Mother': 'Moeder', 'Father': 'Vader', 'Brother': 'Broer', 'Sister': 'Zus', 'Child': 'Kind', 'Children': 'Kinderen', 'Home': 'Thuis', 'Work': 'Werk', 'business': 'bedrijf', 'company': 'bedrijf', 'employee': 'werknemer', 'employer': 'werkgever', 'manager': 'manager', 'client': 'klant', 'meeting': 'vergadering', 'project': 'project', 'product': 'product', 'service': 'dienst', 'office': 'kantoor', 'price': 'prijs', 'cost': 'kosten', 'offer': 'aanbod', 'agreement': 'overeenkomst', 'contract': 'contract', 'market': 'markt', 'school': 'school', 'hospital': 'ziekenhuis', 'bank': 'bank', 'street': 'straat', 'house': 'huis', 'room': 'kamer', 'door': 'deur', 'window': 'raam',
    }},
    'sv': {'folder': 'SV-TO-RW', 'map': {
        'How do you say': 'Hur säger man', 'in Kinyarwanda?': 'på kinyarwanda?', 'What is': 'Vad är', 'What does': 'Vad betyder', 'mean?': 'betyder?', 'Translate this lesson term': 'Översätt detta lektionsord', 'Answer': 'Svar', 'Question': 'Fråga', 'Practice': 'Öva', 'Learn': 'Lär dig', 'Listen': 'Lyssna', 'Read': 'Läs', 'Write': 'Skriv', 'Speak': 'Tala', 'Choose': 'Välj', 'Correct': 'Rätt', 'Word': 'Ord', 'Sentence': 'Mening',
        'Greetings': 'Hälsningar', 'Numbers': 'Tal', 'Family': 'Familj', 'Colors': 'Färger', 'Animals': 'Djur', 'Food': 'Mat', 'Daily Routines': 'Dagliga rutiner', 'Weather': 'Väder', 'Clothing': 'Kläder', 'House': 'Hus', 'Travel': 'Resor', 'Shopping': 'Shopping', 'Restaurant': 'Restaurang', 'Directions': 'Vägbeskrivningar', 'Emotions': 'Känslor', 'Past Tense': 'Dåtid', 'Future Tense': 'Framtid', 'Conditionals': 'Villkor', 'Opinions': 'Åsikter', 'Storytelling': 'Berättande', 'Culture': 'Kultur', 'Days': 'Dagar', 'Business': 'Affärer', 'Debates': 'Debatter', 'Negotiations': 'Förhandlingar', 'Fluency': 'Flyt',
        'Dog': 'Hund', 'Cat': 'Katt', 'Cow': 'Ko', 'Goat': 'Get', 'Sheep': 'Får', 'Pig': 'Gris', 'Chicken': 'Kyckling', 'Rabbit': 'Kanin', 'Bird': 'Fågel', 'Lion': 'Lejon', 'Elephant': 'Elefant', 'Fish': 'Fisk', 'Bee': 'Bi', 'eats': 'äter', 'drinks': 'dricker', 'sleeps': 'sover', 'runs': 'springer', 'flies': 'flyger', 'swims': 'simmar', 'plays': 'leker', 'grass': 'gräs', 'water': 'vatten', 'meat': 'kött', 'milk': 'mjölk', 'Left': 'Vänster', 'Right': 'Höger', 'Straight': 'Rakt fram', 'Front': 'Framför', 'Behind': 'Bakom', 'Back': 'Tillbaka', 'Near': 'Nära', 'Far': 'Långt borta', 'Turn left': 'Sväng vänster', 'Turn right': 'Sväng höger', 'Go straight': 'Gå rakt fram', 'Go back': 'Gå tillbaka', 'Cross the street': 'Gå över gatan', 'Hello': 'Hej', 'Goodbye': 'Hej då', 'Good morning': 'God morgon', 'Good evening': 'God kväll', 'How are you?': 'Hur mår du?', 'I am fine': 'Jag mår bra', 'Tomorrow': 'Imorgon', 'Yesterday': 'Igår', 'Always': 'Alltid', 'Never': 'Aldrig', 'Before': 'Före', 'After': 'Efter', 'Blue': 'Blå', 'Red': 'Röd', 'Green': 'Grön', 'Yellow': 'Gul', 'Black': 'Svart', 'White': 'Vit', 'Orange': 'Orange', 'Brown': 'Brun', 'Purple': 'Lila', 'Happy': 'Glad', 'Sad': 'Ledsen', 'Angry': 'Arg', 'Scared': 'Rädd', 'Name': 'Namn', 'Date': 'Datum', 'Time': 'Tid', 'Friend': 'Vän', 'Mother': 'Mamma', 'Father': 'Pappa', 'Brother': 'Bror', 'Sister': 'Syster', 'Child': 'Barn', 'Children': 'Barn', 'Home': 'Hem', 'Work': 'Arbete', 'business': 'affärer', 'company': 'företag', 'employee': 'anställd', 'employer': 'arbetsgivare', 'manager': 'chef', 'client': 'kund', 'meeting': 'möte', 'project': 'projekt', 'product': 'produkt', 'service': 'tjänst', 'office': 'kontor', 'price': 'pris', 'cost': 'kostnad', 'offer': 'erbjudande', 'agreement': 'avtal', 'contract': 'kontrakt', 'market': 'marknad', 'school': 'skola', 'hospital': 'sjukhus', 'bank': 'bank', 'street': 'gata', 'house': 'hus', 'room': 'rum', 'door': 'dörr', 'window': 'fönster',
    }},
}

PROTECTED = {'id', 'type', 'xp_reward', 'difficulty', 'time_limit_seconds', 'topic', 'audio', 'audio_url', 'audio_file', 'tts_audio', 'image', 'image_url', 'link', 'answer', 'correct_answer', 'correct_sentence', 'correct_response', 'tts_text', 'prompt', 'statement', 'context_sentence', 'bot_message', 'text_with_blank', 'sentence', 'word', 'front', 'back', 'left', 'right'}


def should_protect(value, key):
    return key in PROTECTED and (not isinstance(value, str) or value not in {'Answer', 'Question', 'Translate this lesson term', 'Correct answer', 'Choose an answer'})


def translate_text(value: str, lang: str) -> str:
    if not isinstance(value, str) or value.startswith(('http://', 'https://')):
        return value
    result = value
    for source, target in sorted(LANGUAGES[lang]['map'].items(), key=lambda item: len(item[0]), reverse=True):
        result = re.sub(rf'(?<!\w){re.escape(source)}(?!\w)', target, result, flags=re.IGNORECASE)
    return result


def walk(value, key='', lang='ru'):
    if isinstance(value, dict):
        return {child_key: copy.deepcopy(child) if should_protect(child, child_key) else walk(child, child_key, lang) for child_key, child in value.items()}
    if isinstance(value, list):
        return [walk(item, key, lang) for item in value]
    if isinstance(value, str):
        return translate_text(value, lang)
    return value


def generate(lang: str):
    folder = Path('content') / LANGUAGES[lang]['folder']
    for source_file in sorted(SOURCE_ROOT.rglob('*.yaml')):
        output_file = folder / source_file.relative_to(SOURCE_ROOT)
        output_file.parent.mkdir(parents=True, exist_ok=True)
        source = yaml.safe_load(source_file.read_text(encoding='utf-8').replace("\\'", "'")) or {}
        output_file.write_text(yaml.safe_dump(walk(source, lang=lang), allow_unicode=True, sort_keys=False, width=120), encoding='utf-8')
        print(f'Wrote {output_file}')


def validate(lang: str):
    source_files = sorted(SOURCE_ROOT.rglob('*.yaml'))
    output_files = sorted((Path('content') / LANGUAGES[lang]['folder']).rglob('*.yaml'))
    assert len(source_files) == len(output_files), (lang, len(source_files), len(output_files))
    for source_file, output_file in zip(source_files, output_files):
        source = yaml.safe_load(source_file.read_text(encoding='utf-8').replace("\\'", "'")) or {}
        output = yaml.safe_load(output_file.read_text(encoding='utf-8')) or {}
        assert [e.get('id') for e in source.get('exercises', [])] == [e.get('id') for e in output.get('exercises', [])]
        assert [e.get('xp_reward') for e in source.get('exercises', [])] == [e.get('xp_reward') for e in output.get('exercises', [])]
    print(f'VALID: {lang.upper()} course generated with matching exercise IDs and XP values')


if __name__ == '__main__':
    for language in LANGUAGES:
        generate(language)
        validate(language)
