from __future__ import annotations

import copy
import re
from pathlib import Path

import yaml

SOURCE_ROOT = Path('content/EN-TO-RW/EN-TO-RW')
LANGUAGES = {
    'ga': {'folder': 'GA-TO-RW', 'map': {
        'How do you say': 'Conas a deirtear', 'in Kinyarwanda?': 'i gCinéaruanda?', 'What is': 'Cad é', 'What does': 'Cad is brí le', 'mean?': 'a chiallaíonn?', 'Translate this lesson term': 'Aistrigh téarma an cheachta seo', 'Answer': 'Freagra', 'Question': 'Ceist', 'Practice': 'Cleachtadh', 'Learn': 'Foghlaim', 'Listen': 'Éist', 'Read': 'Léigh', 'Write': 'Scríobh', 'Speak': 'Labhair', 'Choose': 'Roghnaigh', 'Correct': 'Ceart', 'Word': 'Focal', 'Sentence': 'Abairt',
        'Greetings': 'Beannachtaí', 'Numbers': 'Uimhreacha', 'Family': 'Teaghlach', 'Colors': 'Dathanna', 'Animals': 'Ainmhithe', 'Food': 'Bia', 'Daily Routines': 'Gnáthaimh laethúla', 'Weather': 'Aimsir', 'Clothing': 'Éadaí', 'House': 'Teach', 'Travel': 'Taisteal', 'Shopping': 'Siopadóireacht', 'Restaurant': 'Bialann', 'Directions': 'Treoracha', 'Emotions': 'Mothúcháin', 'Past Tense': 'Aimsir chaite', 'Future Tense': 'Aimsir fháistineach', 'Conditionals': 'Coinníollacha', 'Opinions': 'Tuairimí', 'Storytelling': 'Scéalaíocht', 'Culture': 'Cultúr', 'Days': 'Laethanta', 'Business': 'Gnó', 'Debates': 'Díospóireachtaí', 'Negotiations': 'Idirbheartaíocht', 'Fluency': 'Líofacht',
        'Dog': 'Madra', 'Cat': 'Cat', 'Cow': 'Bó', 'Goat': 'Gabhar', 'Sheep': 'Caora', 'Pig': 'Muc', 'Chicken': 'Sicín', 'Rabbit': 'Coinín', 'Bird': 'Éan', 'Lion': 'Leon', 'Elephant': 'Eilifint', 'Fish': 'Iasc', 'Bee': 'Beach', 'eats': 'itheann', 'drinks': 'ólann', 'sleeps': 'codlaíonn', 'runs': 'rith', 'flies': 'eitlíonn', 'swims': 'snámhann', 'plays': 'imríonn', 'grass': 'féar', 'water': 'uisce', 'meat': 'feoil', 'milk': 'bainne', 'Left': 'Clé', 'Right': 'Deas', 'Straight': 'Díreach', 'Front': 'Chun tosaigh', 'Behind': 'Taobh thiar', 'Back': 'Ar ais', 'Near': 'In aice', 'Far': 'I bhfad', 'Turn left': 'Cas ar chlé', 'Turn right': 'Cas ar dheis', 'Go straight': 'Téigh díreach', 'Go back': 'Téigh ar ais', 'Cross the street': 'Trasnaigh an tsráid', 'Hello': 'Dia dhuit', 'Goodbye': 'Slán', 'Good morning': 'Maidin mhaith', 'Good evening': 'Tráthnóna maith', 'How are you?': 'Conas atá tú?', 'I am fine': 'Tá mé go maith', 'Tomorrow': 'Amárach', 'Yesterday': 'Inné', 'Always': 'I gcónaí', 'Never': 'Riamh', 'Before': 'Roimh', 'After': 'Tar éis', 'Blue': 'Gorm', 'Red': 'Dearg', 'Green': 'Glas', 'Yellow': 'Buí', 'Black': 'Dubh', 'White': 'Bán', 'Orange': 'Oráiste', 'Brown': 'Donn', 'Purple': 'Corcra', 'Happy': 'Sásta', 'Sad': 'Brónach', 'Angry': 'Feargach', 'Scared': 'Scanraithe', 'Name': 'Ainm', 'Date': 'Dáta', 'Time': 'Am', 'Friend': 'Cara', 'Mother': 'Máthair', 'Father': 'Athair', 'Brother': 'Deartháir', 'Sister': 'Deirfiúr', 'Child': 'Páiste', 'Children': 'Páistí', 'Home': 'Baile', 'Work': 'Obair', 'business': 'gnó', 'company': 'cuideachta', 'employee': 'fostaí', 'employer': 'fostóir', 'manager': 'bainisteoir', 'client': 'cliant', 'meeting': 'cruinniú', 'project': 'tionscadal', 'product': 'táirge', 'service': 'seirbhís', 'office': 'oifig', 'price': 'praghas', 'cost': 'costas', 'offer': 'tairiscint', 'agreement': 'comhaontú', 'contract': 'conradh', 'market': 'margadh', 'school': 'scoil', 'hospital': 'ospidéal', 'bank': 'banc', 'street': 'sráid', 'house': 'teach', 'room': 'seomra', 'door': 'doras', 'window': 'fuinneog',
    }},
    'el': {'folder': 'EL-TO-RW', 'map': {
        'How do you say': 'Πώς λέμε', 'in Kinyarwanda?': 'στα Κινιαρουάντα;', 'What is': 'Τι είναι', 'What does': 'Τι σημαίνει', 'mean?': 'σημαίνει;', 'Translate this lesson term': 'Μεταφράστε τον όρο αυτού του μαθήματος', 'Answer': 'Απάντηση', 'Question': 'Ερώτηση', 'Practice': 'Εξάσκηση', 'Learn': 'Μάθετε', 'Listen': 'Ακούστε', 'Read': 'Διαβάστε', 'Write': 'Γράψτε', 'Speak': 'Μιλήστε', 'Choose': 'Επιλέξτε', 'Correct': 'Σωστό', 'Word': 'Λέξη', 'Sentence': 'Πρόταση',
        'Greetings': 'Χαιρετισμοί', 'Numbers': 'Αριθμοί', 'Family': 'Οικογένεια', 'Colors': 'Χρώματα', 'Animals': 'Ζώα', 'Food': 'Φαγητό', 'Daily Routines': 'Καθημερινές συνήθειες', 'Weather': 'Καιρός', 'Clothing': 'Ρούχα', 'House': 'Σπίτι', 'Travel': 'Ταξίδια', 'Shopping': 'Αγορές', 'Restaurant': 'Εστιατόριο', 'Directions': 'Οδηγίες', 'Emotions': 'Συναισθήματα', 'Past Tense': 'Παρελθοντικός χρόνος', 'Future Tense': 'Μέλλοντας', 'Conditionals': 'Υποθετικοί λόγοι', 'Opinions': 'Απόψεις', 'Storytelling': 'Αφήγηση ιστοριών', 'Culture': 'Πολιτισμός', 'Days': 'Ημέρες', 'Business': 'Επιχειρήσεις', 'Debates': 'Συζητήσεις', 'Negotiations': 'Διαπραγματεύσεις', 'Fluency': 'Ευχέρεια',
        'Dog': 'Σκύλος', 'Cat': 'Γάτα', 'Cow': 'Αγελάδα', 'Goat': 'Κατσίκα', 'Sheep': 'Πρόβατο', 'Pig': 'Γουρούνι', 'Chicken': 'Κοτόπουλο', 'Rabbit': 'Κουνέλι', 'Bird': 'Πουλί', 'Lion': 'Λιοντάρι', 'Elephant': 'Ελέφαντας', 'Fish': 'Ψάρι', 'Bee': 'Μέλισσα', 'eats': 'τρώει', 'drinks': 'πίνει', 'sleeps': 'κοιμάται', 'runs': 'τρέχει', 'flies': 'πετάει', 'swims': 'κολυμπάει', 'plays': 'παίζει', 'grass': 'γρασίδι', 'water': 'νερό', 'meat': 'κρέας', 'milk': 'γάλα', 'Left': 'Αριστερά', 'Right': 'Δεξιά', 'Straight': 'Ευθεία', 'Front': 'Μπροστά', 'Behind': 'Πίσω', 'Back': 'Πίσω', 'Near': 'Κοντά', 'Far': 'Μακριά', 'Turn left': 'Στρίψτε αριστερά', 'Turn right': 'Στρίψτε δεξιά', 'Go straight': 'Πηγαίνετε ευθεία', 'Go back': 'Γυρίστε πίσω', 'Cross the street': 'Διασχίστε τον δρόμο', 'Hello': 'Γεια σας', 'Goodbye': 'Αντίο', 'Good morning': 'Καλημέρα', 'Good evening': 'Καλησπέρα', 'How are you?': 'Τι κάνεις;', 'I am fine': 'Είμαι καλά', 'Tomorrow': 'Αύριο', 'Yesterday': 'Χθες', 'Always': 'Πάντα', 'Never': 'Ποτέ', 'Before': 'Πριν', 'After': 'Μετά', 'Blue': 'Μπλε', 'Red': 'Κόκκινο', 'Green': 'Πράσινο', 'Yellow': 'Κίτρινο', 'Black': 'Μαύρο', 'White': 'Λευκό', 'Orange': 'Πορτοκαλί', 'Brown': 'Καφέ', 'Purple': 'Μωβ', 'Happy': 'Χαρούμενος', 'Sad': 'Λυπημένος', 'Angry': 'Θυμωμένος', 'Scared': 'Φοβισμένος', 'Name': 'Όνομα', 'Date': 'Ημερομηνία', 'Time': 'Ώρα', 'Friend': 'Φίλος', 'Mother': 'Μητέρα', 'Father': 'Πατέρας', 'Brother': 'Αδελφός', 'Sister': 'Αδελφή', 'Child': 'Παιδί', 'Children': 'Παιδιά', 'Home': 'Σπίτι', 'Work': 'Εργασία', 'business': 'επιχείρηση', 'company': 'εταιρεία', 'employee': 'υπάλληλος', 'employer': 'εργοδότης', 'manager': 'διευθυντής', 'client': 'πελάτης', 'meeting': 'συνάντηση', 'project': 'έργο', 'product': 'προϊόν', 'service': 'υπηρεσία', 'office': 'γραφείο', 'price': 'τιμή', 'cost': 'κόστος', 'offer': 'προσφορά', 'agreement': 'συμφωνία', 'contract': 'συμβόλαιο', 'market': 'αγορά', 'school': 'σχολείο', 'hospital': 'νοσοκομείο', 'bank': 'τράπεζα', 'street': 'δρόμος', 'house': 'σπίτι', 'room': 'δωμάτιο', 'door': 'πόρτα', 'window': 'παράθυρο',
    }},
    'he': {'folder': 'HE-TO-RW', 'map': {
        'How do you say': 'איך אומרים', 'in Kinyarwanda?': 'בקיניארואנדה?', 'What is': 'מה זה', 'What does': 'מה פירוש', 'mean?': 'פירושו?', 'Translate this lesson term': 'תרגם את מונח השיעור הזה', 'Answer': 'תשובה', 'Question': 'שאלה', 'Practice': 'תרגול', 'Learn': 'למדו', 'Listen': 'הקשיבו', 'Read': 'קראו', 'Write': 'כתבו', 'Speak': 'דברו', 'Choose': 'בחרו', 'Correct': 'נכון', 'Word': 'מילה', 'Sentence': 'משפט',
        'Greetings': 'ברכות', 'Numbers': 'מספרים', 'Family': 'משפחה', 'Colors': 'צבעים', 'Animals': 'בעלי חיים', 'Food': 'אוכל', 'Daily Routines': 'שגרה יומית', 'Weather': 'מזג אוויר', 'Clothing': 'בגדים', 'House': 'בית', 'Travel': 'נסיעות', 'Shopping': 'קניות', 'Restaurant': 'מסעדה', 'Directions': 'כיוונים', 'Emotions': 'רגשות', 'Past Tense': 'זמן עבר', 'Future Tense': 'זמן עתיד', 'Conditionals': 'תנאים', 'Opinions': 'דעות', 'Storytelling': 'סיפור סיפורים', 'Culture': 'תרבות', 'Days': 'ימים', 'Business': 'עסקים', 'Debates': 'דיונים', 'Negotiations': 'משא ומתן', 'Fluency': 'שטף',
        'Dog': 'כלב', 'Cat': 'חתול', 'Cow': 'פרה', 'Goat': 'עז', 'Sheep': 'כבשה', 'Pig': 'חזיר', 'Chicken': 'תרנגולת', 'Rabbit': 'ארנב', 'Bird': 'ציפור', 'Lion': 'אריה', 'Elephant': 'פיל', 'Fish': 'דג', 'Bee': 'דבורה', 'eats': 'אוכל', 'drinks': 'שותה', 'sleeps': 'ישן', 'runs': 'רץ', 'flies': 'עף', 'swims': 'שוחה', 'plays': 'משחק', 'grass': 'דשא', 'water': 'מים', 'meat': 'בשר', 'milk': 'חלב', 'Left': 'שמאל', 'Right': 'ימין', 'Straight': 'ישר', 'Front': 'קדימה', 'Behind': 'מאחור', 'Back': 'אחורה', 'Near': 'קרוב', 'Far': 'רחוק', 'Turn left': 'פנו שמאלה', 'Turn right': 'פנו ימינה', 'Go straight': 'לכו ישר', 'Go back': 'חזרו', 'Cross the street': 'חצו את הרחוב', 'Hello': 'שלום', 'Goodbye': 'להתראות', 'Good morning': 'בוקר טוב', 'Good evening': 'ערב טוב', 'How are you?': 'מה שלומך?', 'I am fine': 'אני בסדר', 'Tomorrow': 'מחר', 'Yesterday': 'אתמול', 'Always': 'תמיד', 'Never': 'אף פעם', 'Before': 'לפני', 'After': 'אחרי', 'Blue': 'כחול', 'Red': 'אדום', 'Green': 'ירוק', 'Yellow': 'צהוב', 'Black': 'שחור', 'White': 'לבן', 'Orange': 'כתום', 'Brown': 'חום', 'Purple': 'סגול', 'Happy': 'שמח', 'Sad': 'עצוב', 'Angry': 'כועס', 'Scared': 'מפוחד', 'Name': 'שם', 'Date': 'תאריך', 'Time': 'זמן', 'Friend': 'חבר', 'Mother': 'אמא', 'Father': 'אבא', 'Brother': 'אח', 'Sister': 'אחות', 'Child': 'ילד', 'Children': 'ילדים', 'Home': 'בית', 'Work': 'עבודה', 'business': 'עסק', 'company': 'חברה', 'employee': 'עובד', 'employer': 'מעסיק', 'manager': 'מנהל', 'client': 'לקוח', 'meeting': 'פגישה', 'project': 'פרויקט', 'product': 'מוצר', 'service': 'שירות', 'office': 'משרד', 'price': 'מחיר', 'cost': 'עלות', 'offer': 'הצעה', 'agreement': 'הסכם', 'contract': 'חוזה', 'market': 'שוק', 'school': 'בית ספר', 'hospital': 'בית חולים', 'bank': 'בנק', 'street': 'רחוב', 'house': 'בית', 'room': 'חדר', 'door': 'דלת', 'window': 'חלון',
    }},
    'pl': {'folder': 'PL-TO-RW', 'map': {
        'How do you say': 'Jak się mówi', 'in Kinyarwanda?': 'po kinjaruandzku?', 'What is': 'Co to jest', 'What does': 'Co oznacza', 'mean?': 'oznacza?', 'Translate this lesson term': 'Przetłumacz termin z tej lekcji', 'Answer': 'Odpowiedź', 'Question': 'Pytanie', 'Practice': 'Ćwiczenie', 'Learn': 'Nauka', 'Listen': 'Słuchaj', 'Read': 'Czytaj', 'Write': 'Pisz', 'Speak': 'Mów', 'Choose': 'Wybierz', 'Correct': 'Poprawny', 'Word': 'Słowo', 'Sentence': 'Zdanie',
        'Greetings': 'Powitania', 'Numbers': 'Liczby', 'Family': 'Rodzina', 'Colors': 'Kolory', 'Animals': 'Zwierzęta', 'Food': 'Jedzenie', 'Daily Routines': 'Codzienne czynności', 'Weather': 'Pogoda', 'Clothing': 'Ubrania', 'House': 'Dom', 'Travel': 'Podróże', 'Shopping': 'Zakupy', 'Restaurant': 'Restauracja', 'Directions': 'Kierunki', 'Emotions': 'Emocje', 'Past Tense': 'Czas przeszły', 'Future Tense': 'Czas przyszły', 'Conditionals': 'Tryby warunkowe', 'Opinions': 'Opinie', 'Storytelling': 'Opowiadanie historii', 'Culture': 'Kultura', 'Days': 'Dni', 'Business': 'Biznes', 'Debates': 'Debaty', 'Negotiations': 'Negocjacje', 'Fluency': 'Płynność',
        'Dog': 'Pies', 'Cat': 'Kot', 'Cow': 'Krowa', 'Goat': 'Koza', 'Sheep': 'Owca', 'Pig': 'Świnia', 'Chicken': 'Kurczak', 'Rabbit': 'Królik', 'Bird': 'Ptak', 'Lion': 'Lew', 'Elephant': 'Słoń', 'Fish': 'Ryba', 'Bee': 'Pszczoła', 'eats': 'je', 'drinks': 'pije', 'sleeps': 'śpi', 'runs': 'biega', 'flies': 'lata', 'swims': 'pływa', 'plays': 'bawi się', 'grass': 'trawa', 'water': 'woda', 'meat': 'mięso', 'milk': 'mleko', 'Left': 'Lewo', 'Right': 'Prawo', 'Straight': 'Prosto', 'Front': 'Przód', 'Behind': 'Tył', 'Back': 'Z powrotem', 'Near': 'Blisko', 'Far': 'Daleko', 'Turn left': 'Skręć w lewo', 'Turn right': 'Skręć w prawo', 'Go straight': 'Idź prosto', 'Go back': 'Wróć', 'Cross the street': 'Przejdź przez ulicę', 'Hello': 'Cześć', 'Goodbye': 'Do widzenia', 'Good morning': 'Dzień dobry', 'Good evening': 'Dobry wieczór', 'How are you?': 'Jak się masz?', 'I am fine': 'Mam się dobrze', 'Tomorrow': 'Jutro', 'Yesterday': 'Wczoraj', 'Always': 'Zawsze', 'Never': 'Nigdy', 'Before': 'Przed', 'After': 'Po', 'Blue': 'Niebieski', 'Red': 'Czerwony', 'Green': 'Zielony', 'Yellow': 'Żółty', 'Black': 'Czarny', 'White': 'Biały', 'Orange': 'Pomarańczowy', 'Brown': 'Brązowy', 'Purple': 'Fioletowy', 'Happy': 'Szczęśliwy', 'Sad': 'Smutny', 'Angry': 'Zły', 'Scared': 'Przestraszony', 'Name': 'Imię', 'Date': 'Data', 'Time': 'Czas', 'Friend': 'Przyjaciel', 'Mother': 'Matka', 'Father': 'Ojciec', 'Brother': 'Brat', 'Sister': 'Siostra', 'Child': 'Dziecko', 'Children': 'Dzieci', 'Home': 'Dom', 'Work': 'Praca', 'business': 'biznes', 'company': 'firma', 'employee': 'pracownik', 'employer': 'pracodawca', 'manager': 'kierownik', 'client': 'klient', 'meeting': 'spotkanie', 'project': 'projekt', 'product': 'produkt', 'service': 'usługa', 'office': 'biuro', 'price': 'cena', 'cost': 'koszt', 'offer': 'oferta', 'agreement': 'umowa', 'contract': 'kontrakt', 'market': 'rynek', 'school': 'szkoła', 'hospital': 'szpital', 'bank': 'bank', 'street': 'ulica', 'house': 'dom', 'room': 'pokój', 'door': 'drzwi', 'window': 'okno',
    }},
    'no': {'folder': 'NO-TO-RW', 'map': {
        'How do you say': 'Hvordan sier man', 'in Kinyarwanda?': 'på kinyarwanda?', 'What is': 'Hva er', 'What does': 'Hva betyr', 'mean?': 'betyr?', 'Translate this lesson term': 'Oversett dette leksjonsordet', 'Answer': 'Svar', 'Question': 'Spørsmål', 'Practice': 'Øv', 'Learn': 'Lær', 'Listen': 'Lytt', 'Read': 'Les', 'Write': 'Skriv', 'Speak': 'Snakk', 'Choose': 'Velg', 'Correct': 'Riktig', 'Word': 'Ord', 'Sentence': 'Setning',
        'Greetings': 'Hilsener', 'Numbers': 'Tall', 'Family': 'Familie', 'Colors': 'Farger', 'Animals': 'Dyr', 'Food': 'Mat', 'Daily Routines': 'Daglige rutiner', 'Weather': 'Vær', 'Clothing': 'Klær', 'House': 'Hus', 'Travel': 'Reiser', 'Shopping': 'Shopping', 'Restaurant': 'Restaurant', 'Directions': 'Veibeskrivelser', 'Emotions': 'Følelser', 'Past Tense': 'Fortid', 'Future Tense': 'Fremtid', 'Conditionals': 'Betingelser', 'Opinions': 'Meniger', 'Storytelling': 'Historiefortelling', 'Culture': 'Kultur', 'Days': 'Dager', 'Business': 'Forretninger', 'Debates': 'Debatter', 'Negotiations': 'Forhandlinger', 'Fluency': 'Flyt',
        'Dog': 'Hund', 'Cat': 'Katt', 'Cow': 'Ku', 'Goat': 'Geit', 'Sheep': 'Sau', 'Pig': 'Gris', 'Chicken': 'Kylling', 'Rabbit': 'Kanin', 'Bird': 'Fugl', 'Lion': 'Løve', 'Elephant': 'Elefant', 'Fish': 'Fisk', 'Bee': 'Bie', 'eats': 'spiser', 'drinks': 'drikker', 'sleeps': 'sover', 'runs': 'løper', 'flies': 'flyr', 'swims': 'svømmer', 'plays': 'leker', 'grass': 'gress', 'water': 'vann', 'meat': 'kjøtt', 'milk': 'melk', 'Left': 'Venstre', 'Right': 'Høyre', 'Straight': 'Rett frem', 'Front': 'Foran', 'Behind': 'Bak', 'Back': 'Tilbake', 'Near': 'Nær', 'Far': 'Langt borte', 'Turn left': 'Sving til venstre', 'Turn right': 'Sving til høyre', 'Go straight': 'Gå rett frem', 'Go back': 'Gå tilbake', 'Cross the street': 'Kryss gaten', 'Hello': 'Hei', 'Goodbye': 'Ha det', 'Good morning': 'God morgen', 'Good evening': 'God kveld', 'How are you?': 'Hvordan har du det?', 'I am fine': 'Jeg har det bra', 'Tomorrow': 'I morgen', 'Yesterday': 'I går', 'Always': 'Alltid', 'Never': 'Aldri', 'Before': 'Før', 'After': 'Etter', 'Blue': 'Blå', 'Red': 'Rød', 'Green': 'Grønn', 'Yellow': 'Gul', 'Black': 'Svart', 'White': 'Hvit', 'Orange': 'Oransje', 'Brown': 'Brun', 'Purple': 'Lilla', 'Happy': 'Glad', 'Sad': 'Trist', 'Angry': 'Sint', 'Scared': 'Redd', 'Name': 'Navn', 'Date': 'Dato', 'Time': 'Tid', 'Friend': 'Venn', 'Mother': 'Mor', 'Father': 'Far', 'Brother': 'Bror', 'Sister': 'Søster', 'Child': 'Barn', 'Children': 'Barn', 'Home': 'Hjem', 'Work': 'Arbeid', 'business': 'forretning', 'company': 'selskap', 'employee': 'ansatt', 'employer': 'arbeidsgiver', 'manager': 'leder', 'client': 'klient', 'meeting': 'møte', 'project': 'prosjekt', 'product': 'produkt', 'service': 'tjeneste', 'office': 'kontor', 'price': 'pris', 'cost': 'kostnad', 'offer': 'tilbud', 'agreement': 'avtale', 'contract': 'kontrakt', 'market': 'marked', 'school': 'skole', 'hospital': 'sykehus', 'bank': 'bank', 'street': 'gate', 'house': 'hus', 'room': 'rom', 'door': 'dør', 'window': 'vindu',
    }},
}

PROTECTED = {'id', 'type', 'xp_reward', 'difficulty', 'time_limit_seconds', 'topic', 'audio', 'audio_url', 'audio_file', 'tts_audio', 'image', 'image_url', 'link', 'answer', 'correct_answer', 'correct_sentence', 'correct_response', 'tts_text', 'prompt', 'statement', 'context_sentence', 'bot_message', 'text_with_blank', 'sentence', 'word', 'front', 'back', 'left', 'right'}


def should_protect(value, key):
    return key in PROTECTED and (not isinstance(value, str) or value not in {'Answer', 'Question', 'Translate this lesson term', 'Correct answer', 'Choose an answer'})


def translate_text(value: str, lang: str) -> str:
    if not isinstance(value, str) or value.startswith(('http://', 'https://')):
        return value
    result = value
    for source, target in sorted(LANGUAGES[lang]['map'].items(), key=lambda item: len(item[0]), reverse=True):
        result = re.sub(rf'(?<!\w){re.escape(source)}(?!\w)', target, result, flags=re.IGNORECASE)
    return result


def walk(value, key='', lang='ga'):
    if isinstance(value, dict):
        return {child_key: copy.deepcopy(child) if should_protect(child, child_key) else walk(child, child_key, lang) for child_key, child in value.items()}
    if isinstance(value, list):
        return [walk(item, key, lang) for item in value]
    if isinstance(value, str):
        return translate_text(value, lang)
    return value


def generate(lang: str):
    folder = Path('content') / LANGUAGES[lang]['folder']
    for source_file in sorted(SOURCE_ROOT.rglob('*.yaml')):
        output_file = folder / source_file.relative_to(SOURCE_ROOT)
        output_file.parent.mkdir(parents=True, exist_ok=True)
        source = yaml.safe_load(source_file.read_text(encoding='utf-8').replace("\\'", "'")) or {}
        output_file.write_text(yaml.safe_dump(walk(source, lang=lang), allow_unicode=True, sort_keys=False, width=120), encoding='utf-8')
        print(f'Wrote {output_file}')


def validate(lang: str):
    source_files = sorted(SOURCE_ROOT.rglob('*.yaml'))
    output_files = sorted((Path('content') / LANGUAGES[lang]['folder']).rglob('*.yaml'))
    assert len(source_files) == len(output_files), (lang, len(source_files), len(output_files))
    for source_file, output_file in zip(source_files, output_files):
        source = yaml.safe_load(source_file.read_text(encoding='utf-8').replace("\\'", "'")) or {}
        output = yaml.safe_load(output_file.read_text(encoding='utf-8')) or {}
        assert [e.get('id') for e in source.get('exercises', [])] == [e.get('id') for e in output.get('exercises', [])]
        assert [e.get('xp_reward') for e in source.get('exercises', [])] == [e.get('xp_reward') for e in output.get('exercises', [])]
    print(f'VALID: {lang.upper()} course generated with matching exercise IDs and XP values')


if __name__ == '__main__':
    for language in LANGUAGES:
        generate(language)
        validate(language)
